In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [24]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc  = time.time()

print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]

toc = time.time()
print("For loop:" + str(1000*(toc-tic)) + "ms")

Vectorized version:1.9989013671875ms
For loop:625.2326965332031ms


In [18]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [22]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [26]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [27]:
a = np.random.randn(5)
print(a.shape)

(5,)


In [30]:
print(a)
print(a.T)
print(np.dot(a,a.T))

[-1.33500916  2.33855681  0.73520722  1.13245433  1.20374438]
[-1.33500916  2.33855681  0.73520722  1.13245433  1.20374438]
10.5230803921
[[ 0.01852147 -0.015616    0.16933182 -0.05427925  0.04435866]
 [-0.015616    0.01316631 -0.14276867  0.04576444 -0.0374001 ]
 [ 0.16933182 -0.14276867  1.54810936 -0.49624585  0.40554728]
 [-0.05427925  0.04576444 -0.49624585  0.15907141 -0.12999802]
 [ 0.04435866 -0.0374001   0.40554728 -0.12999802  0.10623836]]


In [31]:
a = np.random.randn(5,1)
print(np.dot(a,a.T))

#Always use (5,1) amd not (5,)

[[ 0.26893748 -0.29737952 -0.17856533 -0.27450697 -0.63097272]
 [-0.29737952  0.32882951  0.19744988  0.30353803  0.69770255]
 [-0.17856533  0.19744988  0.1185613   0.18226329  0.4189444 ]
 [-0.27450697  0.30353803  0.18226329  0.28019181  0.6440397 ]
 [-0.63097272  0.69770255  0.4189444   0.6440397   1.48036851]]
